# Generated by Django 3.2 on 2021-06-25 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('about_image1', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Subject', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('whatsapp_no', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('customer_image1', models.ImageField(upload_to='productimg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('excost', models.FloatField(default=0.0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Actual_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('expenditure_price', models.FloatField(default=0.0)),
                ('as_per', models.CharField(choices=[('Day', 'Day'), ('Second', 'Second'), ('Minute', 'Minute'), ('Square Fit', 'Square Fit'), ('Week', 'Week'), ('Year', 'Year'), ('Hour', 'Hour'), ('Inch', 'Inch'), ('Centimeter', 'Centimeter')], max_length=15)),
                ('description', models.TextField()),
                ('Service_image1', models.ImageField(upload_to='productimg')),
                ('Service_image2', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_costs', models.FloatField()),
                ('total_pad', models.FloatField(default=0.0)),
                ('remaing_amount', models.FloatField(default=0.0)),
                ('total_profit', models.FloatField(default=0.0)),
                ('expencess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.expence')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Call Me', 'Call Me'), ('Service is Start', 'Service is Start'), ('Wait For Our Message', 'Wait For Our Message'), ('Service is Complete', 'Service is Complete'), ('Cancel', 'Cancel'), ('Service is near to end', 'Service is near to end'), ('This time is not Available', 'This time is not Available')], default='Pending', max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('document', models.FileField(default=None, upload_to='productimg')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='feed_back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('name_of_serves', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rate_us', models.CharField(choices=[('30', '30'), ('50', '50'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('90', '90'), ('99', '99'), ('100', '100')], max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.EmailField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
