# Generated by Django 3.2 on 2021-07-16 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210716_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='msg_time',
            field=models.DateTimeField(auto_now_add=True,default = 1 ),
            preserve_default=False,
        ),
    ]
