# Generated by Django 3.2 on 2021-07-17 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_us_msg_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.services'),
            preserve_default=False,
        ),
    ]
