# Generated by Django 3.2 on 2021-07-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_expence_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expence',
            name='service',
        ),
    ]
